export const Loading = {
    CHANGE_STATE : 'CHANGE_STATE',
    INIT: 'INIT',
    LOADING: 'LOADING',
    LOADED: 'LOADED',
    ERROR: 'ERROR'
}

export const Data = {
    LOAD_INTO_STATE: 'DATA_LOAD_INTO_STATE',
    CHANGE_STATUS : 'DATA_CHANGE_STATUS',
    CHANGE_FEHLEROBJECT: 'DATA_CHANGE_FEHLEROBJECT',
    CHANGE_NOTIZ: 'DATA_CHANGE_NOTIZ'
}

export const Fehler = {
    LOAD_INTO_STATE: 'FEHLER_LOAD_INTO_STATE',
    DELETE: 'FEHLER_DELETE',
    UPDATE: 'FEHLER_UPDATE',
    CREATE: 'FEHLER_CREATE'
}

export const Berater = {
    LOAD_INTO_STATE: 'BERATER_LOAD_INTO_STATE',
    DELETE: 'BERATER_DELETE',
    UPDATE: 'BERATER_UPDATE',
    CREATE: 'BERATER_CREATE'
}